In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset=pd.read_csv('Social_Network_Ads.csv')

In [4]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [6]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [7]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [8]:
independent=dataset[['Age', 'EstimatedSalary','Gender_Male']]

In [9]:
independent

     Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [10]:
dependent=dataset['Purchased']

In [11]:
dependent

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [16]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
param_grid={ "kernel": ["poly"],
    "C": [0.1, 1, 10],
    "degree": [2, 3, 4],
    "gamma": ["scale", 0.01, 0.1],
    "coef0": [0.0, 0.5, 1.0]}
grid=GridSearchCV(SVC(),param_grid, refit=True, verbose=3, n_jobs=-1,scoring='f1_weighted')
grid.fit(X_train,y_train)

Fitting 5 folds for each of 81 candidates, totalling 405 fits

GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10], 'coef0': [0.0, 0.5, 1.0],
                         'degree': [2, 3, 4], 'gamma': ['scale', 0.01, 0.1],
                         'kernel': ['poly']},
             scoring='f1_weighted', verbose=3)

In [17]:
re=grid.cv_results_

In [18]:
re

{'mean_fit_time': array([0.00505114, 0.00468283, 0.00438242, 0.00415535, 0.00426822,
        0.00402865, 0.00376701, 0.00381622, 0.0041472 , 0.00381188,
        0.00360026, 0.00438004, 0.00415277, 0.00415335, 0.00411654,
        0.00379391, 0.00445971, 0.00323248, 0.00297856, 0.00411282,
        0.00419521, 0.00401073, 0.00442162, 0.00390697, 0.00331054,
        0.00452127, 0.00351377, 0.00466671, 0.00510406, 0.00374031,
        0.00384512, 0.00402899, 0.00418577, 0.00405173, 0.00469871,
        0.00399914, 0.00344191, 0.00431471, 0.00358734, 0.00349154,
        0.00399485, 0.0036612 , 0.0031662 , 0.00416188, 0.00314775,
        0.00298533, 0.003371  , 0.00363798, 0.00371685, 0.00375276,
        0.0033968 , 0.00405865, 0.00371399, 0.00349646, 0.00519238,
        0.00413041, 0.00394011, 0.00547686, 0.00422573, 0.00366735,
        0.00915565, 0.00378799, 0.00412035, 0.004142  , 0.00379162,
        0.00423608, 0.0044981 , 0.00368872, 0.00353994, 0.00519676,
        0.00423746, 0.00371561, 0.00434265, 0.00355248, 0.00383844,
        0.00682073, 0.00411086, 0.0033268 , 0.00628767, 0.0040451 ,
        0.00391145]),
 'std_fit_time': array([0.00073502, 0.00102894, 0.00130577, 0.00078393, 0.00064847,
        0.00050237, 0.0008642 , 0.00068129, 0.00048132, 0.00036542,
        0.00082627, 0.00061085, 0.00032666, 0.00048905, 0.00060794,
        0.00069679, 0.00074499, 0.00054269, 0.00065088, 0.00039657,
        0.00113259, 0.00028804, 0.00101797, 0.0002377 , 0.00065429,
        0.00040999, 0.00053368, 0.00027652, 0.00072692, 0.00072983,
        0.00055255, 0.00048472, 0.00112185, 0.00092339, 0.0002518 ,
        0.000638  , 0.00052267, 0.00027006, 0.00013928, 0.00037987,
        0.0003756 , 0.00029381, 0.00059092, 0.00094429, 0.00089397,
        0.00068556, 0.00092072, 0.00049917, 0.00037776, 0.0004045 ,
        0.00053494, 0.0007525 , 0.00053276, 0.0006302 , 0.0004072 ,
        0.00071272, 0.00102981, 0.00045857, 0.00049056, 0.0006631 ,
        0.00305149, 0.0006118 , 0.0001902 , 0.00098664, 0.00041039,
        0.00044291, 0.00115552, 0.00059385, 0.00010896, 0.00058671,
        0.00033865, 0.00038476, 0.0006791 , 0.00055041, 0.00018079,
        0.0022712 , 0.00074535, 0.00041643, 0.00102936, 0.00064324,
        0.00034486]),
 'mean_score_time': array([0.00617714, 0.00557289, 0.0057055 , 0.00541048, 0.00476165,
        0.00492635, 0.00459399, 0.00484662, 0.00505252, 0.00539064,
        0.00507998, 0.00580401, 0.00517049, 0.00573635, 0.00575581,
        0.00556974, 0.005899  , 0.00444756, 0.00437856, 0.0054544 ,
        0.00602412, 0.00476098, 0.00526834, 0.00488701, 0.00503373,
        0.00557389, 0.00558114, 0.00507064, 0.0052474 , 0.00529466,
        0.00529189, 0.00512114, 0.00496454, 0.00479784, 0.00536485,
        0.00539975, 0.00463781, 0.00550432, 0.00539403, 0.00579038,
        0.00502892, 0.00505419, 0.00481644, 0.00431395, 0.00497742,
        0.00465503, 0.00465565, 0.00565486, 0.00459819, 0.00484338,
        0.0047895 , 0.00522237, 0.00462437, 0.00531206, 0.00514226,
        0.00584035, 0.00505586, 0.00543504, 0.00562816, 0.00567684,
        0.00570159, 0.00608597, 0.00529261, 0.00521107, 0.00576611,
        0.00460682, 0.00475931, 0.00521402, 0.00455942, 0.0047925 ,
        0.00515456, 0.00496287, 0.00539632, 0.0052958 , 0.00462112,
        0.00507016, 0.00522356, 0.0054729 , 0.00515256, 0.00525646,
        0.00516615]),
 'std_score_time': array([0.00059435, 0.00124541, 0.00104248, 0.00051386, 0.00079254,
        0.00085533, 0.00058328, 0.00089094, 0.00081934, 0.00112383,
        0.00048145, 0.0007521 , 0.0007602 , 0.00075672, 0.00085645,
        0.00090388, 0.00064163, 0.0005819 , 0.00073374, 0.00107106,
        0.00049706, 0.0010215 , 0.00126452, 0.00061014, 0.00087919,
        0.00050364, 0.00030108, 0.00098915, 0.00076969, 0.00112544,
        0.00061035, 0.00081614, 0.00105558, 0.00054656, 0.00012853,
        0.00040952, 0.00048151, 0.0007188 , 0.0003843 , 0.00089029,
        0.00116829, 0.00084458, 0.00082474, 0.00101683, 0.00051613,
        0.00042756, 0.00076263, 0.0006158 , 0.00042935, 0.00085944,
        0.00090464, 0.00062745, 0.00064505, 0.00026002, 0.00032868,
        0.00073531, 0.00051401, 0.00091523, 0.00094395, 0.00051574,
        0.00061593, 0.00056868, 0.00079739, 0.00057116, 0.0005761 ,
        0.00068038, 0.0004427 , 0.00063077, 0.00085806, 0.00056612,
        0.00060697, 0.00067935, 0.00069121, 0.00071696, 0.00043255,
        0.00063427, 0.00046954, 0.00094902, 0.00042081, 0.00083492,
        0.00030956]),
 'param_C': masked_array(data=[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
                    0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
                    0.1, 0.1, 0.1, 0.1, 0.1, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 10.0,
                    10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0,
                    10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0,
                    10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False],
        fill_value=1e+20),
 'param_coef0': masked_array(data=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5,
                    0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
                    0.5, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0,
                    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.5,
                    0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False],
        fill_value=1e+20),
 'param_degree': masked_array(data=[2, 2, 2, 3, 3, 3, 4, 4, 4, 2, 2, 2, 3, 3, 3, 4, 4, 4,
                    2, 2, 2, 3, 3, 3, 4, 4, 4, 2, 2, 2, 3, 3, 3, 4, 4, 4,
                    2, 2, 2, 3, 3, 3, 4, 4, 4, 2, 2, 2, 3, 3, 3, 4, 4, 4,
                    2, 2, 2, 3, 3, 3, 4, 4, 4, 2, 2, 2, 3, 3, 3, 4, 4, 4,
                    2, 2, 2, 3, 3, 3, 4, 4, 4],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False],
        fill_value=999999),
 'param_gamma': masked_array(data=['scale', 0.01, 0.1, 'scale', 0.01, 0.1, 'scale', 0.01,
                    0.1, 'scale', 0.01, 0.1, 'scale', 0.01, 0.1, 'scale',
                    0.01, 0.1, 'scale', 0.01, 0.1, 'scale', 0.01, 0.1,
                    'scale', 0.01, 0.1, 'scale', 0.01, 0.1, 'scale', 0.01,
                    0.1, 'scale', 0.01, 0.1, 'scale', 0.01, 0.1, 'scale',
                    0.01, 0.1, 'scale', 0.01, 0.1, 'scale', 0.01, 0.1,
                    'scale', 0.01, 0.1, 'scale', 0.01, 0.1, 'scale', 0.01,
                    0.1, 'scale', 0.01, 0.1, 'scale', 0.01, 0.1, 'scale',
                    0.01, 0.1, 'scale', 0.01, 0.1, 'scale', 0.01, 0.1,
                    'scale', 0.01, 0.1, 'scale', 0.01, 0.1, 'scale', 0.01,
                    0.1],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_kernel': masked_array(data=['poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 0.1,
   'coef0': 0.0,
   'degree': 2,
   'gamma': 'scale',
   'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.0, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.0, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.0, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.0, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.0, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.0, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.0, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.0, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 0.5, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 0.1, 'coef0': 1.0, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.0, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 0.5, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 1, 'coef0': 1.0, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.0, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 0.5, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 2, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 2, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 2, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 3, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 3, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 4, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 4, 'gamma': 0.01, 'kernel': 'poly'},
  {'C': 10, 'coef0': 1.0, 'degree': 4, 'gamma': 0.1, 'kernel': 'poly'}],
 'split0_test_score': array([0.71551986, 0.50977944, 0.50977944, 0.76863283, 0.50977944,
        0.50977944, 0.79332011, 0.50977944, 0.50977944, 0.83969611,
        0.50977944, 0.75198413, 0.86162702, 0.50977944, 0.74275589,
        0.86162702, 0.50977944, 0.74275589, 0.82209189, 0.50977944,
        0.75198413, 0.86162702, 0.50977944, 0.77629048, 0.86487093,
        0.50977944, 0.82209189, 0.79962013, 0.50977944, 0.71551986,
        0.79962013, 0.50977944, 0.65615232, 0.79962013, 0.50977944,
        0.50977944, 0.86487093, 0.69988187, 0.82209189, 0.84714126,
        0.6867284 , 0.86162702, 0.84714126, 0.58851791, 0.86162702,
        0.84714126, 0.72656607, 0.84381092, 0.88535594, 0.72656607,
        0.84381092, 0.84714126, 0.79962013, 0.84381092, 0.79962013,
        0.50977944, 0.79962013, 0.79962013, 0.50977944, 0.79332011,
        0.79962013, 0.50977944, 0.79332011, 0.84714126, 0.77629048,
        0.84714126, 0.84714126, 0.79962013, 0.86487093, 0.86747844,
        0.79962013, 0.84714126, 0.86747844, 0.77629048, 0.86747844,
        0.84714126, 0.79962013, 0.86747844, 0.86747844, 0.79962013,
        0.88535594]),
 'split1_test_score': array([0.776838  , 0.52530017, 0.52530017, 0.7278083 , 0.52530017,
        0.52530017, 0.67393431, 0.52530017, 0.52530017, 0.86696784,
        0.52530017, 0.776838  , 0.84671353, 0.52530017, 0.75285092,
        0.84671353, 0.52530017, 0.7278083 , 0.86696784, 0.52530017,
        0.75988083, 0.86696784, 0.52530017, 0.80462774, 0.88679245,
        0.52530017, 0.86696784, 0.8221546 , 0.52530017, 0.64473079,
        0.80462774, 0.52530017, 0.67393431, 0.84370219, 0.52530017,
        0.52530017, 0.88810678, 0.75285092, 0.86696784, 0.88679245,
        0.67393431, 0.86696784, 0.88679245, 0.64087522, 0.86696784,
        0.86875226, 0.74311219, 0.8490566 , 0.88679245, 0.74311219,
        0.86696784, 0.88679245, 0.74311219, 0.86875226, 0.8221546 ,
        0.52530017, 0.8221546 , 0.80839191, 0.52530017, 0.75988083,
        0.8221546 , 0.52530017, 0.67393431, 0.88810678, 0.78728354,
        0.86875226, 0.86696784, 0.76555329, 0.86875226, 0.86696784,

In [19]:
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [20]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'C': 10, 'coef0': 1.0, 'degree': 3, 'gamma': 0.1, 'kernel': 'poly'}: 0.9183922682195829

In [21]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[78  7]
 [ 4 45]]

In [22]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.95      0.92      0.93        85
           1       0.87      0.92      0.89        49

    accuracy                           0.92       134
   macro avg       0.91      0.92      0.91       134
weighted avg       0.92      0.92      0.92       134

In [24]:
table=pd.DataFrame.from_dict(re)

In [25]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_coef0,param_degree,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005051,0.000735,0.006177,0.000594,0.1,0.0,2,scale,poly,"{'C': 0.1, 'coef0': 0.0, 'degree': 2, 'gamma':...",0.715520,0.776838,0.617764,0.747667,0.772377,0.726033,0.058360,56
1,0.004683,0.001029,0.005573,0.001245,0.1,0.0,2,0.01,poly,"{'C': 0.1, 'coef0': 0.0, 'degree': 2, 'gamma':...",0.509779,0.525300,0.501410,0.501410,0.501410,0.507862,0.009302,64
2,0.004382,0.001306,0.005705,0.001042,0.1,0.0,2,0.1,poly,"{'C': 0.1, 'coef0': 0.0, 'degree': 2, 'gamma':...",0.509779,0.525300,0.501410,0.501410,0.501410,0.507862,0.009302,64
3,0.004155,0.000784,0.005410,0.000514,0.1,0.0,3,scale,poly,"{'C': 0.1, 'coef0': 0.0, 'degree': 3, 'gamma':...",0.768633,0.727808,0.621589,0.862442,0.789723,0.754039,0.079333,52
4,0.004268,0.000648,0.004762,0.000793,0.1,0.0,3,0.01,poly,"{'C': 0.1, 'coef0': 0.0, 'degree': 3, 'gamma':...",0.509779,0.525300,0.501410,0.501410,0.501410,0.507862,0.009302,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,0.004111,0.000745,0.005224,0.000470,10.0,1.0,3,0.01,poly,"{'C': 10, 'coef0': 1.0, 'degree': 3, 'gamma': ...",0.799620,0.811321,0.727648,0.943041,0.922185,0.840763,0.080554,34
77,0.003327,0.000416,0.005473,0.000949,10.0,1.0,3,0.1,poly,"{'C': 10, 'coef0': 1.0, 'degree': 3, 'gamma': ...",0.867478,0.886792,0.850543,0.962636,0.943041,0.902098,0.043432,1
78,0.006288,0.001029,0.005153,0.000421,10.0,1.0,4,scale,poly,"{'C': 10, 'coef0': 1.0, 'degree': 4, 'gamma': ...",0.867478,0.866968,0.869709,0.925272,0.903610,0.886607,0.023754,20
79,0.004045,0.000643,0.005256,0.000835,10.0,1.0,4,0.01,poly,"{'C': 10, 'coef0': 1.0, 'degree': 4, 'gamma': ...",0.799620,0.831253,0.749387,0.943041,0.981014,0.860863,0.087457,31
80,0.003911,0.000345,0.005166,0.000310,10.0,1.0,4,0.1,poly,"{'C': 10, 'coef0': 1.0, 'degree': 4, 'gamma': ...",0.885356,0.886792,0.851527,0.962636,0.923510,0.901964,0.037935,3