In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('Social_Network_Ads.csv')

In [3]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [6]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [7]:
independent=dataset[['Age', 'EstimatedSalary','Gender_Male']]

In [8]:
independent

     Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [9]:
dependent=dataset['Purchased']

In [10]:
dependent

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [200,],
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt', 'log2'],
    'bootstrap': [True]
}


grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train_, y_train)

Fitting 5 folds for each of 810 candidates, totalling 4050 fits

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'bootstrap': [True, False],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [None, 10, 20, 30, 50],
                         'max_features': ['sqrt', 'log2', None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [200]},
             scoring='f1', verbose=3)

In [17]:
re=grid.cv_results_

In [18]:
grid_predictions = grid.predict(X_test_) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [19]:
print(grid.best_params_)

{'bootstrap': True, 'criterion': 'entropy', 'max_depth': 20, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'min_samples_split': 5, 'n_estimators': 200}

In [20]:
table=pd.DataFrame.from_dict(re)

In [21]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_bootstrap,param_criterion,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.583743,0.016232,0.028094,0.001427,True,gini,None,sqrt,1,2,200,"{'bootstrap': True, 'criterion': 'gini', 'max_...",0.800000,0.842105,0.809524,0.900000,0.923077,0.854941,0.048824,514
1,0.580519,0.008704,0.028284,0.002024,True,gini,None,sqrt,1,5,200,"{'bootstrap': True, 'criterion': 'gini', 'max_...",0.800000,0.850000,0.837209,0.926829,0.947368,0.872281,0.055794,214
2,0.548728,0.024337,0.029351,0.003402,True,gini,None,sqrt,1,10,200,"{'bootstrap': True, 'criterion': 'gini', 'max_...",0.833333,0.850000,0.837209,0.926829,0.947368,0.878948,0.048239,44
3,0.554980,0.008990,0.031190,0.001774,True,gini,None,sqrt,2,2,200,"{'bootstrap': True, 'criterion': 'gini', 'max_...",0.800000,0.842105,0.837209,0.926829,0.947368,0.870702,0.056509,320
4,0.561892,0.011231,0.031137,0.002047,True,gini,None,sqrt,2,5,200,"{'bootstrap': True, 'criterion': 'gini', 'max_...",0.800000,0.842105,0.837209,0.926829,0.947368,0.870702,0.056509,320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805,0.453570,0.005827,0.027324,0.000944,False,log_loss,50,None,2,5,200,"{'bootstrap': False, 'criterion': 'log_loss', ...",0.800000,0.789474,0.780488,0.829268,0.833333,0.806513,0.021200,791
806,0.447984,0.007454,0.027245,0.000508,False,log_loss,50,None,2,10,200,"{'bootstrap': False, 'criterion': 'log_loss', ...",0.777778,0.789474,0.809524,0.809524,0.918919,0.821044,0.050425,729
807,0.448001,0.000971,0.026952,0.000350,False,log_loss,50,None,4,2,200,"{'bootstrap': False, 'criterion': 'log_loss', ...",0.645161,0.787879,0.850000,0.900000,0.918919,0.820392,0.098676,741
808,0.438654,0.007652,0.025598,0.001678,False,log_loss,50,None,4,5,200,"{'bootstrap': False, 'criterion': 'log_loss', ...",0.645161,0.787879,0.850000,0.900000,0.918919,0.820392,0.098676,741
809,0.418350,0.023236,0.017487,0.001319,False,log_loss,50,None,4,10,200,"{'bootstrap': False, 'criterion': 'log_loss', ...",0.764706,0.764706,0.850000,0.900000,0.947368,0.845356,0.072695,597

In [22]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'bootstrap': True, 'criterion': 'entropy', 'max_depth': 20, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'min_samples_split': 5, 'n_estimators': 200}: 0.9186591315268318

In [23]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[77  8]
 [ 3 46]]

In [24]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.96      0.91      0.93        85
           1       0.85      0.94      0.89        49

    accuracy                           0.92       134
   macro avg       0.91      0.92      0.91       134
weighted avg       0.92      0.92      0.92       134

In [27]:
table_pr=pd.DataFrame()

In [29]:
print(X_test)

     Age  EstimatedSalary  Gender_Male
132   30            87000            1
309   38            50000            0
341   35            75000            1
196   30            79000            0
246   35            50000            0
..   ...              ...          ...
168   29           148000            1
150   26            15000            0
393   60            42000            1
66    24            19000            1
240   42           149000            1

[134 rows x 3 columns]